// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mddmbsowcskbnooloiox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kZG1ic293Y3NrYm5vb2xvaW94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0OTEzMzQsImV4cCI6MjA2NjA2NzMzNH0.QU1tjfdRUohDkMbzwnmT6jwp6AfF_eU_MVmq4c3sxyI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});