// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgceigacnqguankbpiua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnY2VpZ2FjbnFndWFua2JwaXVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMDMwMDMsImV4cCI6MjA2Njg3OTAwM30.p3TIrp7kCusod9Y7pFmrYozU1s6F3FyhVJqLMPwvSWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});